/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-08-12 03:49:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exam05_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("*{\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("#container{\r\n");
      out.write("\tpadding: 30px 20px;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("\tfont-size: large;\r\n");
      out.write("\tborder-left: 10px solid #7BAEB5;\r\n");
      out.write("\tborder-bottom: 1px solid #7BAEB5;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("}\r\n");
      out.write("div#comment_write{\r\n");
      out.write("\tpadding: 20px 15px;\r\n");
      out.write("\tborder-bottom: 1px solid #7BAEB5;\r\n");
      out.write("}\r\n");
      out.write("div#comment_write label{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth:80px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("input[name='user_name'], textarea[name='comment'] {\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tpadding: 3px 10px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 150%;\r\n");
      out.write("}\r\n");
      out.write("textarea[name='comment'] {\r\n");
      out.write("\twidth: 380px;\r\n");
      out.write("\theight: 90px;\r\n");
      out.write("}\r\n");
      out.write("/* 앞으로 생성될 태그의 CSS 설정 */\r\n");
      out.write(".comment_item{\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tborder-bottom: 1px dotted #CCC;\r\n");
      out.write("\tline-height: 150%\r\n");
      out.write("}\r\n");
      out.write(".comment_item .writer {\r\n");
      out.write("\tcolor: #555;\r\n");
      out.write("\tline-height: 200%;\r\n");
      out.write("}\r\n");
      out.write(".comment_item .writer input {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".comment_item .writer .name{\r\n");
      out.write("\tcolor: #222;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t/* 새로운 글을 화면에 추가하기 위한 함수 */\r\n");
      out.write("\tfunction addNewItem(num, writer, content, datetime) {\r\n");
      out.write("\t\t//alert(\"num\" +num + \"\\n\"+\"user_name\" +user_name + \"\\n\"+\"content\" + content+ \"\\n\"+\"datetime\" + datetime+ \"\\n\")\r\n");
      out.write("\t\t// 새로운 덧글이 추가될 li태그\r\n");
      out.write("\t\tvar new_li = $(\"<li>\");\r\n");
      out.write("\t\tnew_li.attr(\"data-num\", num);\r\n");
      out.write("\t\tnew_li.addClass(\"comment_item\");\r\n");
      out.write("\t\t// 작성자 정보가 지정될 <p>태그\r\n");
      out.write("\t\tvar writer_p = $(\"<p>\");\r\n");
      out.write("\t\twriter_p.addClass(\"writer\");\r\n");
      out.write("\t\t// 작성자 정보의 이름\r\n");
      out.write("\t\tvar name_span = $(\"<span>\");\r\n");
      out.write("\t\tname_span.addClass(\"name\");\r\n");
      out.write("\t\tname_span.html(writer + \"님\");\r\n");
      out.write("\t\t// 작성일시\r\n");
      out.write("\t\tvar date_span = $(\"<span>\");\r\n");
      out.write("\t\tdate_span.html(\" / \" + datetime + \" \");\r\n");
      out.write("\t\t// 삭제하기 버튼\r\n");
      out.write("\t\tvar del_input = $(\"<input>\");\r\n");
      out.write("\t\tdel_input.attr({\r\n");
      out.write("\t\t\t\"type\" : \"button\",\r\n");
      out.write("\t\t\t\"value\" : \"삭제하기\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tdel_input.addClass(\"delete_btn\");\r\n");
      out.write("\t\t// 내용\r\n");
      out.write("\t\tvar content_p = $(\"<p>\");\r\n");
      out.write("\t\tcontent_p.html(content);\r\n");
      out.write("\t\t// 조립하기\r\n");
      out.write("\t\twriter_p.append(name_span).append(date_span).append(del_input);\r\n");
      out.write("\t\tnew_li.append(writer_p).append(content_p);\r\n");
      out.write("\t\t$(\"#comment_list\").append(new_li);\r\n");
      out.write("\t}\r\n");
      out.write("\t/* 맨 마지막에 작동 */\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t/* 기본 덧글 목록 불러오기 */\r\n");
      out.write("\t\t$.get(\"ajax/comment/comment_list.xml\",{},function(data){\r\n");
      out.write("\t\t\t// 읽어들인 XML에서 \"item\"태그를 찾아 반복처리\r\n");
      out.write("\t\t\t$(data).find(\"item\").each(function() {\n");
      out.write("\t\t\t\tvar num = $(this).find(\"num\").text();\r\n");
      out.write("\t\t\t\tvar writer = $(this).find(\"writer\").text();\r\n");
      out.write("\t\t\t\tvar content = $(this).find(\"content\").text();\r\n");
      out.write("\t\t\t\tvar datetime = $(this).find(\"datetime\").text();\r\n");
      out.write("\t\t\t\taddNewItem(num, writer, content, datetime);\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}).fail(function() {\n");
      out.write("\t\t\talert(\"덧글 목록을 불러오는데 실패하였습니다. 잠시후에 다시 시도해 주세요\");\n");
      out.write("\t\t});\r\n");
      out.write("\t\t/* 덧글 내용 저장 이벤트 */\r\n");
      out.write("\t\t$(\"#comment_form\").submit(function() {\n");
      out.write("\t\t\t// 작성자 이름에 대한 입력 검사\r\n");
      out.write("\t\t\tif(!$(\"#user_name\").val()){\r\n");
      out.write("\t\t\t\talert(\"이름을 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#user_name\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else if(!$(\"#comment\").val()){\r\n");
      out.write("\t\t\t\talert(\"내용을 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#comment\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 글저장을 위한 post방식의 Ajax 연동 처리\r\n");
      out.write("\t\t\tvar url = \"ajax/comment/comment_write.jsp\";\r\n");
      out.write("\t\t\t$.post(url, $(this).serialize(), function(data) {\r\n");
      out.write("\t\t\t\talert(\"test2\");\r\n");
      out.write("\t\t\t\t// XML에서 \"result\"태그의 값을 추출해서 식으로 변환    / eval : boolean값으로 변환\r\n");
      out.write("\t\t\t\tvar result = eval($(data).find(\"result\").text());\r\n");
      out.write("\t\t\t\t// 결과가 저장 실패를 의미한다면, 에러메시지 출력후 처리 중단\r\n");
      out.write("\t\t\t\tif(!result){\r\n");
      out.write("\t\t\t\t\talert($(data).find(\"message\").text());\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\talert(\"test3\");\r\n");
      out.write("\t\t\t\t// 데이터 추출\r\n");
      out.write("\t\t\t\tvar num = $(data).find(\"num\").text();\r\n");
      out.write("\t\t\t\tvar writer = $(data).find(\"writer\").text();\r\n");
      out.write("\t\t\t\tvar content = $(data).find(\"content\").text();\r\n");
      out.write("\t\t\t\tvar datetime = $(data).find(\"datetime\").text();\r\n");
      out.write("\t\t\t\talert(\"result\" +result + \"\\n\"+\"num\" +num + \"\\n\"+\"user_name\" +writer + \"\\n\"+\"content\" + content+ \"\\n\"+\"datetime\" + datetime+ \"\\n\");\r\n");
      out.write("\t\t\t\t// 함수 호출하여 li태그 추가\r\n");
      out.write("\t\t\t\taddNewItem(num, writer, content, datetime);\r\n");
      out.write("\t\t\t}).fail(function() {\r\n");
      out.write("\t\t\t\talert(\"덧글 목록을 불러오는데 실패하였습니다. 잠시후에 다시 시도해 주세요\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t});\r\n");
      out.write("\t\t/* 삭제 버튼 클릭시에 항목 삭제하도록 미리 지정  */\r\n");
      out.write("\t\t$(document).on(\"click\",\".delete_btn\", function() {\r\n");
      out.write("\t\t\tif(confirm(\"정말 선택하신 항목을 삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t// 덧글 삭제를 할 JSP 파일\r\n");
      out.write("\t\t\t\tvar url = \"ajax/comment/comment_delete.jsp\";\r\n");
      out.write("\t\t\t\t// 글 번호 얻기\r\n");
      out.write("\t\t\t\tvar num = $(this).parents(\"li\").attr(\"data-num\");\r\n");
      out.write("\t\t\t\t// 삭제 대상\r\n");
      out.write("\t\t\t\tvar target = $(this).parents(\".comment_item\");\r\n");
      out.write("\t\t\t\t// 글 번호를 통하여 삭제를 요청함\r\n");
      out.write("\t\t\t\t$.post(url, {\"num\": num}, function(data) {\r\n");
      out.write("\t\t\t\t\t// result 값 추출\r\n");
      out.write("\t\t\t\t\tvar result = eval($(data).find(\"result\").text());\r\n");
      out.write("\t\t\t\t\t// 결과 메시지\r\n");
      out.write("\t\t\t\t\tvar message = $(data).find(\"message\").text();\r\n");
      out.write("\t\t\t\t\t// 메시지 출력\r\n");
      out.write("\t\t\t\t\talert(message);\r\n");
      out.write("\t\t\t\t\t// DB에서 데이터가 삭제되면, 해당 내용을 화면에서 삭제\r\n");
      out.write("\t\t\t\t\tif(result){\r\n");
      out.write("\t\t\t\t\t\ttarget.remove();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}).fail(function() {\n");
      out.write("\t\t\t\t\talert(\"덧글 삭제에 실패했습니다. 잠시후에 다시 시도해 주세요\" );\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\t<h1>jQuery Comment</h1>\r\n");
      out.write("\t<div id=\"comment_write\">\r\n");
      out.write("\t\t<form action=\"\" id=\"comment_form\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"user_name\">작성자</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"user_name\" id=\"user_name\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"저장하기\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"comment\">덧글 내용</label>\r\n");
      out.write("\t\t\t\t<textarea name=\"comment\" id=\"comment\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<ul id=\"comment_list\">\r\n");
      out.write("\t\t<!-- 여기에 동적 생성 요소가 들어감 -->\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
